In [1]:
# Installing Tensorflow
#!pip install tensorflow --user

# Installing Keras, it runs on TensorFlow
#!pip install --upgrade keras

# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

C:\Users\vishk\AppData\Roaming\Python\Python37\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\vishk\AppData\Roaming\Python\Python37\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\Users\vishk\AppData\Roaming\Python\Python37\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
  stacklevel=1)


In [13]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')

In [14]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   
6          7    15592531  Bartlett          822    France    Male   50   
7          8    15656148    Obinna          376   Germany  Female   29   
8          9    15792365        He          501    France    Male   44   
9         10    15592389        H?          684    France    Male   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [15]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [16]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [17]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [18]:
X[:,1:]

array([['France', 'Female', 42, ..., 1, 1, 101348.88],
       ['Spain', 'Female', 41, ..., 0, 1, 112542.58],
       ['France', 'Female', 42, ..., 1, 0, 113931.57],
       ...,
       ['France', 'Female', 36, ..., 0, 1, 42085.58],
       ['Germany', 'Male', 42, ..., 1, 0, 92888.52],
       ['France', 'Female', 28, ..., 1, 0, 38190.78]], dtype=object)

In [19]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [20]:
X[:,1]

array(['France', 'Spain', 'France', ..., 'France', 'Germany', 'France'],
      dtype=object)

In [10]:
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [11]:
X[:,1]

array([0, 2, 0, ..., 0, 1, 0], dtype=object)

In [21]:
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:] #To overcome dummy variable trap
X

TypeError: __init__() got an unexpected keyword argument 'categorical_features'

In [11]:
pd.DataFrame(X).head()

0    1      2    3     4    5          6    7    8    9         10
0  0.0  0.0  619.0  0.0  42.0  2.0       0.00  1.0  1.0  1.0  101348.88
1  0.0  1.0  608.0  0.0  41.0  1.0   83807.86  1.0  0.0  1.0  112542.58
2  0.0  0.0  502.0  0.0  42.0  8.0  159660.80  3.0  1.0  0.0  113931.57
3  0.0  0.0  699.0  0.0  39.0  1.0       0.00  2.0  0.0  0.0   93826.63
4  0.0  1.0  850.0  0.0  43.0  2.0  125510.82  1.0  1.0  1.0   79084.10

In [12]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [13]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
pd.DataFrame(X_train).head()

0         1         2         3         4         5         6  \
0 -0.569844  1.743090  0.169582 -1.091687 -0.464608  0.006661 -1.215717   
1  1.754865 -0.573694 -2.304559  0.916013  0.301026 -1.377440 -0.006312   
2 -0.569844 -0.573694 -1.191196 -1.091687 -0.943129 -1.031415  0.579935   
3 -0.569844  1.743090  0.035566  0.916013  0.109617  0.006661  0.473128   
4 -0.569844  1.743090  2.056114 -1.091687  1.736588  1.044737  0.810193   

          7         8         9        10  
0  0.809503  0.642595 -1.032270  1.106432  
1 -0.921591  0.642595  0.968738 -0.748664  
2 -0.921591  0.642595 -1.032270  1.485335  
3 -0.921591  0.642595 -1.032270  1.276528  
4  0.809503  0.642595  0.968738  0.558378

In [15]:
#!pip install tensorflow==2.0.0b1 --ignore-installed --user
#!pip install tensorflow --user

In [16]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
import tensorflow
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.
C:\Users\vishk\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\vishk\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\vishk\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\vishk\AppData\Roa

In [17]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

In [18]:
# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [19]:
# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
#soft max function for more than 2 output variables

In [20]:
# Compiling the ANN means applying SGD on NN
# optimizer: Algorithm(SGD) one of the type is adam, to be applied for finding best weights
# logarthmic loss function is binary_crossentropy else categorical_crossentropy(>2)
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

W1217 07:13:25.043720 23596 deprecation.py:323] From C:\Users\vishk\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [21]:
# Fitting the ANN to the Training set
#batch size: Number of samples per gradient update
#Number of epochs to train the model. An epoch is an iteration over the entire x and y data provided
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

W1217 07:13:26.289287 23596 deprecation_wrapper.py:119] From C:\Users\vishk\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.



Epoch 1/100
8000/8000 [==============================] - 2s 301us/step - loss: 0.4864 - accuracy: 0.7961
Epoch 2/100
8000/8000 [==============================] - 2s 230us/step - loss: 0.4280 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 242us/step - loss: 0.4226 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 2s 232us/step - loss: 0.4187 - accuracy: 0.8183
Epoch 5/100
8000/8000 [==============================] - 2s 242us/step - loss: 0.4167 - accuracy: 0.8265
Epoch 6/100
8000/8000 [==============================] - 2s 235us/step - loss: 0.4148 - accuracy: 0.8285
Epoch 7/100
8000/8000 [==============================] - 2s 231us/step - loss: 0.4131 - accuracy: 0.8304
Epoch 8/100
8000/8000 [==============================] - 2s 220us/step - loss: 0.4122 - accuracy: 0.8316
Epoch 9/100
8000/8000 [==============================] - 2s 251us/step - loss: 0.4110 - accuracy: 0.8319
Epoch 10/100
8000/8000 [==============================]

In [22]:
# Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [23]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [24]:
cm

array([[1537,   58],
       [ 260,  145]], dtype=int64)

In [25]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import make_scorer
scoring = {'accuracy': make_scorer(accuracy_score),
            'prec': 'precision'}

In [26]:
print("Train Accuracy {:.2%}".format(accuracy_score(y_test,y_pred)))

Train Accuracy 84.10%
